# Generated by Django 5.1.5 on 2025-02-10 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id_cargos', models.AutoField(primary_key=True, serialize=False)),
                ('cargos', models.CharField(max_length=60)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriasProductos',
            fields=[
                ('id_categorias', models.AutoField(primary_key=True, serialize=False)),
                ('categorias', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_clientes', models.AutoField(primary_key=True, serialize=False)),
                ('nombreC', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('ci_o_ruc', models.CharField(max_length=20, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Descuentos',
            fields=[
                ('id_descuento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('porcentaje', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id_horarios', models.AutoField(primary_key=True, serialize=False)),
                ('desde', models.TimeField()),
                ('hasta', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_metodos', models.AutoField(primary_key=True, serialize=False)),
                ('metodos', models.CharField(max_length=40)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedores', models.AutoField(primary_key=True, serialize=False)),
                ('nombrePEE', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_productos', models.AutoField(primary_key=True, serialize=False)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('precio', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('nombreP', models.CharField(max_length=70)),
                ('id_categorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SuperStock.categoriasproductos')),
            ],
        ),
        migrations.CreateModel(
            name='DescuentosProductos',
            fields=[
                ('id_descuentos', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('descuento_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SuperStock.descuentos')),
                ('id_productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SuperStock.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_entrada', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SuperStock.productos')),
                ('id_proveedores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SuperStock.proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cargos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SuperStock.cargos')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SuperStock.horarios')),
                ('nombreU', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_ventas', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('id_clientes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SuperStock.clientes')),
                ('id_metodos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SuperStock.metodopago')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SuperStock.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DetallesVentas',
            fields=[
                ('id_detalles_venta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('id_productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SuperStock.productos')),
                ('id_ventas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SuperStock.ventas')),
            ],
        ),
    ]
