# Generated by Django 5.1.5 on 2025-02-12 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperStock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='id_productos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SuperStock.productos'),
        ),
    ]
