# Generated by Django 5.1.5 on 2025-02-12 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperStock', '0003_ventas_cantidad_delete_detallesventas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='id_productos',
        ),
        migrations.CreateModel(
            name='DetallesVentas',
            fields=[
                ('id_detalles_venta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('id_productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SuperStock.productos')),
                ('id_ventas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SuperStock.ventas')),
            ],
        ),
    ]
