# Generated by Django 5.1.5 on 2025-02-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperStock', '0004_remove_ventas_cantidad_remove_ventas_id_productos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='id_productos',
            field=models.ManyToManyField(to='SuperStock.productos'),
        ),
    ]
