# Generated by Django 5.1.5 on 2025-02-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperStock', '0005_ventas_id_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
