# Generated by Django 5.1.5 on 2025-02-12 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SuperStock', '0006_ventas_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='id_productos',
        ),
    ]
