# Generated by Django 5.1.5 on 2025-02-13 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SuperStock', '0008_ventas_id_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='id_productos',
        ),
    ]
