# Generated by Django 5.1.5 on 2025-02-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperStock', '0009_remove_ventas_id_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesventas',
            name='cantidad',
            field=models.CharField(max_length=150),
        ),
    ]
