# Generated by Django 5.1.5 on 2025-02-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperStock', '0010_alter_detallesventas_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuentosproductos',
            name='valor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
