# Generated by Django 5.1.5 on 2025-02-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperStock', '0011_alter_descuentosproductos_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargos',
            name='in_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='categoriasproductos',
            name='in_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='in_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='descuentos',
            name='in_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='descuentosproductos',
            name='in_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='detallesventas',
            name='in_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='in_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='in_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='in_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='in_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='in_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='in_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ventas',
            name='in_active',
            field=models.BooleanField(default=True),
        ),
    ]
