# Generated by Django 5.1.5 on 2025-02-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperStock', '0012_cargos_in_active_categoriasproductos_in_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallesventas',
            name='id_productos',
        ),
        migrations.AddField(
            model_name='detallesventas',
            name='id_productos',
            field=models.ManyToManyField(to='SuperStock.productos'),
        ),
    ]
