# Generated by Django 5.1.5 on 2025-02-19 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SuperStock', '0013_remove_detallesventas_id_productos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='cargos',
            new_name='cargues',
        ),
    ]
