# Generated by Django 5.1.5 on 2025-02-21 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperStock', '0014_rename_cargos_usuario_cargues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesventas',
            name='id_ventas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SuperStock.ventas', unique=True),
        ),
    ]
