# Generated by Django 5.2 on 2025-06-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperStock', '0015_alter_detallesventas_id_ventas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_compra', models.DateTimeField()),
                ('ubicacion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id_marcas', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='productos',
            name='precioCost',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='salario',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
