# Generated by Django 5.2 on 2025-06-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperStock', '0016_equipos_marcas_productos_preciocost_usuario_salario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='precioCost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
