# Generated by Django 5.2 on 2025-06-05 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperStock', '0017_alter_productos_preciocost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesventas',
            name='id_ventas',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SuperStock.ventas'),
        ),
    ]
