# Generated by Django 5.2 on 2025-06-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperStock', '0018_alter_detallesventas_id_ventas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='id_clientes',
        ),
        migrations.AlterField(
            model_name='clientes',
            name='ci_o_ruc',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
